### ISSUE TITLE
Add ability to assign 3 (or more?) flow meters in local storage mode

### ISSUE THREAD

**Issue by angrypiratebrewing** [johnnyruz/kegbot-android#2]
Currently when running the app in local storage mode you're only able to assign 2 flow meters (kegboard.flow0 - pin 2, and kegboard.flow1 - pin 3) to taps.
Flow meters attached to pin 20/21 (kegboard.flow2 and flow3) are detected by kegtab app but cannot be assigned to a tap - the drop down menu does not display them as an option to select.
Arduino Mega with CH340 chip.

**Comment by johnnyruz** [comment]
This is definitely a "hack" and I'll try to work on a more elegant solution to dynamically detecting and adding flow meters, but it should get you over the hump for your installation.

I'll also move towards contributing fixes to the main Kegbot project rather than my fork.

In the meantime, here's the latest APK that creates 4 flow meters on the local DB. You'll most likely have to uninstall the old version or at least "Clear Data" before installing this new one.

[APK HERE](https://drive.google.com/open?id=1bzbf2k65H1SQTL0f1rzsvqDblqHoigej)

**Comment by angrypiratebrewing** [comment]
Bang on, @johnnyruz !
My testing shows it's all working perfectly.
Now to put it into the kegerator..

**Comment by johnnyruz** [comment]
Sounds great! Glad I could help out!

**Comment by angrypiratebrewing** [comment]
Hey @johnnyruz , you've already helped me out a lot, but wondering if you have much experience setting up kegbot server? I have installed ubuntu on a spare laptop I have, but have tried multiple times and every time a different issue. I have just put a fresh install of ubuntu on the machine and have installed teamviewer - if you're able to help out flick me an email at nealebbett@gmail.com
Would really appreciate it!
Cheers,
